{
  "ingress":[
    {"hostname":"starculator.space", "originRequest":{}, "service":"http://192.168.1.23:8080"},
    {"hostname":"code.starculator.space", "originRequest":{}, "service":"http://192.168.1.23:8081"},
    {"hostname":"dev.starculator.space", "originRequest":{}, "service":"http://192.168.1.23:8082"},
    {"hostname":"backend.starculator.space", "originRequest":{}, "service":"http://192.168.1.23:8000"},
    {"service":"http_status:404"}
  ],
  "warp-routing":{"enabled":false}
}
