# docker-compose.yml
version: '3.8'
services:
  webserver:
    image: nginx:latest
    container_name: webserver
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/html:/usr/share/nginx/html
    networks:
      - webnet
    depends_on:
      - backend
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - webserver
      - code-server
      - backend
    networks:
      - webnet
    volumes:
      - ./config.yml:/etc/cloudflared/config.yml
    restart: unless-stopped

  code-server:
    image: codercom/code-server:latest
    container_name: code-server
    environment:
      - PASSWORD=${CODE_SERVER_PASSWORD}
    ports:
      - "8081:8080"
    networks:
      - webnet
    volumes:
      - ../:/home/coder/project:rw
    user: "1001:1001"
    stdin_open: true
    tty: true
    restart: unless-stopped

  database:
    image: postgres:latest
    container_name: database
    environment:
      - POSTGRES_USER=symfony
      - POSTGRES_PASSWORD=${SYMFONY_PASSWORD}
      - POSTGRES_DB=symfony
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - webnet
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile_dev
    container_name: backend
    user: "1001:1001"
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html:rw
    environment:
      - APP_ENV=dev
      - DATABASE_URL=postgresql://symfony:${SYMFONY_PASSWORD}@database:5432/symfony?serverVersion=15&charset=utf8
    networks:
      - webnet
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile_dev
    container_name: frontend
    ports:
      - "8082:5173"
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true
    networks:
      - webnet
    profiles:
      - dev
    restart: unless-stopped

networks:
  webnet:
    driver: bridge

volumes:
  pgdata: